### ISSUE TITLE
Use view object/presenter

### ISSUE THREAD

**Issue by azranel** [NetguruCodeCollege/team_echo_project#35]
https://github.com/NetguruCodeCollege/team_echo_project/blob/7bd1231eea0c860f582a8dd2ca3b9eb407cc2559/app/controllers/denounces_controller.rb#L10-L15

More info about view objects/presenters here: http://blog.codeclimate.com/blog/2012/10/17/7-ways-to-decompose-fat-activerecord-models/

**Comment by krismichalski** [comment]
This part of the app was rewritten so it's no longer necessary :)
I think...
