### ISSUE TITLE
Refactor spec

### ISSUE THREAD

**Issue by azranel** [NetguruCodeCollege/team_echo_project#36]
https://github.com/NetguruCodeCollege/team_echo_project/blob/7bd1231eea0c860f582a8dd2ca3b9eb407cc2559/spec/models/denounce_spec.rb#L1-L28

1. Use factory_girl to create models with filled data (you can also use FFaker to generate random data).
2. Place tested methods in`describe`. For example you place tests for method `#call` in `describe "#call" do` block.
3. Add specs for associations.

**Comment by krismichalski** [comment]
@azranel Done :)
